### PR TITLE
Move test execution to runner file, refactor output

### LINKED ISSUE #121: Output package has too much responsibilities
The `output/cli.go` has more responsibilities than formatting the output.

 - It measures the execution time
 - Counts succeeded and failed tests

The `runtime` should be responsible for that, the `output` should only receive the data and process it.

### PR DESCRIPTION
**Pull request by dylanhitt**
Closes #121. 

#### TODO:

- [x] Migrate `runtime.Start` to it's own file `runner.go`
- [x] Stream `TestResults` to `output` in `runtime`
- [x] Aggregate `TestResults` to a single `struct Result`
- [x] Add `FileName` to `TestCase` struct when executing against a `dir`
- [x] Define a single `OutputWriter` to be used in both `Runtime` and for `out.PrintSummary`
- [x] Test `runner.go`
- [x] Converge `struct Result`s in `Test_Command` when executing against a `dir`
- [x] Switch `output` to `go/template`

## Checklist

 - [x] Added unit / integration tests for windows, macOS and Linux? 
 - [ ] Added a changelog entry in [CHANGELOG.md](../CHANGELOG.md)?
 - [ ] Updated the documentation ([README.md](../README.md), [docs](../docs))?
 - [x] Does your change work on `Linux`, `Windows` and `macOS`?

### CODE REVIEW

**Comment by dylanhitt** [comment]
Mainly just trying to organize my thoughts.

I elected to implement `runner.go` in the `runtime` package do to moving `runner` into it's own package would require a major refactor of `runtime`. Pulling the execution out currently causes a circular dependency as all the executors reside in `runtime`. `runtime` be broken up could beneficial as well.

**Comment by dylanhitt** [comment]
@SimonBaeumer when you get a chance would you mind taking a look. My above comment explains some of my decisions. I'm hesitant to write tests. I'm not a big fan of my `go/template` implementation, it's kinda tough to implement the output colors and still get the benefit of using `template`.  I will implement test based upon how your feedback goes. I will enjoy moving execution to `runner.go` as passing the the channel doesn't feel very forced anymore.

Let me know what you think, Im looking forward to your feedback. I hope all is well

Cheers

**Comment by SimonBaeumer** [comment]
Hey @dylanhitt!
Nice to see your pull request, it looks really good to me for a first approach!

File: pkg/output/template.go [hunk 1]
```diff
@@ -0,0 +1,111 @@
+package output
```
Comment (SimonBaeumer) [inline pkg/output/template.go:1]: Renaming `template.go` to `cli_template.go`, or moving all files related to the cli output inside an `output/cli/` directory.
Indeed, this is a really picky comment :D

File: pkg/runtime/runner.go [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+	"time"
+)
+
+// Runner holds the config and executes the desired runtime env
+type Runner struct {
+	Nodes []Node
+}
+
+// Execute the runner
+func (r *Runner) Execute(tests []TestCase) <-chan TestResult {
```
Comment (SimonBaeumer) [inline pkg/runtime/runner.go:16]: :+1:

File: pkg/runtime/runtime.go [hunk 3]
```diff
@@ -30,22 +25,28 @@ const (
 )
 
 // NewRuntime creates a new runtime and inits default nodes
-func NewRuntime(nodes ...Node) Runtime {
+func NewRuntime(out *output.OutputWriter, nodes ...Node) Runtime {
```
Comment (SimonBaeumer) [inline pkg/runtime/runtime.go:28]: :+1:

File: pkg/runtime/runtime.go [hunk 4]
```diff
@@ -118,140 +120,41 @@ type TestResult struct {
...
-					ExecUser:     n.DockerExecUser,
-					RegistryPass: n.Pass,
-					RegistryUser: n.User,
-				}
-			case "":
-				return NewLocalExecutor()
-			default:
-				log.Fatal(fmt.Sprintf("Node type %s not found for node %s", n.Type, n.Name))
-			}
+func (r *Runtime) Start(tests []TestCase) output.Result {
```
Comment (SimonBaeumer) [inline pkg/runtime/runtime.go:127]: Your implementation is heading in the right direction. 
At first I pointed out that the output should not now anything about the `runtime`.
Now maybe it would be nicer if the runtime doesn't know anything about the output, atm it is highly depends on the `output` package because 
1. it is called directly
2. return an `output.Result` as the aggregated result, which is a little bit weird because the runtime package always uses it's own structs - and suddenly it uses the `output.Result` because of circular dependencies (which a normal dev would never see)

My proposal in this case would be to integrate a light weight "event"-system which is just a struct which holds some functions which are called at a specific time, i.e. a test finished.
In Kubernetes this would be called a `SharedInformer`, I would like to stick to `EventHandler` because it is more understandable.

```go
type EventHandler struct {
    TestFinsihed func(TestCase)
    RuntimeFinished func(Result)
}

// Start starts the given test suite and executes all tests
func (r *Runtime) Start(tests []TestCase) Result {
	testCh := r.Runner.Execute(tests)
       result := Result{} // Result is defined like the output.Result but located inside the runtime
	start := time.Now()
	for tr := range testCh {
		tr := convertTestResult(tr)
	        // Instead of printing the result the TestFinished function gets called
                //r.Output.PrintResult(tr)
               r.EventHandler.TestFinished(tr)

		if !tr.Success {
			result.Failed++
		}

		result.TestResults = append(result.TestResults, tr)
	}
	result.Duration = time.Since(start)
        
        r.EventHandler.RuntimeFinished()
	return result
}
```

It would be possible to add more listeners, even adding a slice of listeners allowing multiple functions to hook into the execution.
Now if an output should be configured it could be by adding the event handlers, i.e. inside the `output` package
```go
func NewEventHandler() runtime.EventHandler {
   testFunc := function (testResult runtime.TestResult) {
       // printResult...
   }

   finishFunc := function (result runtime.Result) {
       // printSummary...
   }
}
```

The `EventHandler` could be added as a property to the `runtime.Runtime` struct. 
What are your thoughts on this? 
This should make testing easier too.

**Comment by SimonBaeumer** [comment]
If you need any help on formatting issues let me know - I can help you with the annoying tasks ;)

File: pkg/runtime/runtime.go (hunk 4 above)
Comment (dylanhitt) [reply pkg/runtime/runtime.go:127]: I like the idea of an EventListener. I don't think we quite have a use for `r.EventHandler.RuntimeFinished()` this yet, but i see where you're going. You did lose me  at the very end and I think it's mainly I'm losing where structs should be defined. So:

```golang
type EventHandler struct {
    TestFinsihed func(TestCase)
    RuntimeFinished func(Result)
}
```
^This is defined in `runtime`

```golang
// convert runtime.TestResult to output.TestResult
func convertTestResult(tr TestResult) output.TestResult {
	testResult := output.TestResult{
		FileName:       tr.TestCase.FileName,
		Title:          tr.TestCase.Title,
		Node:           tr.Node,
		Tries:          tr.Tries,
		Success:        tr.ValidationResult.Success,
		FailedProperty: tr.FailedProperty,
		Diff:           tr.ValidationResult.Diff,
		Error:          tr.TestCase.Result.Error,
	}

	return testResult
}

```
^this will be moved to output in some capacity. Ideally there will be some conversion that takes place in `r.EventHandler.TestFinished(tr)`

```golang
func NewEventHandler() runtime.EventHandler {
   testFunc := function (testResult runtime.TestResult) {
       // printResult...
   }

   finishFunc := function (result runtime.Result) {
       // printSummary...
   }
}
```
^this code would belong in `output`? If this code is in output. We would need something on these lines in app
```golang
r := runtime.NewRuntime(out.NewEventHander, s.Nodes...)
result := r.Start(tests)
```
and runtime is 
```golang
type Runtime struct {
	Runner *Runner
	event     EventHandler
}
```

I was. going to suggest that eventhandler should get it's own package rather than being generated over in `output`.  However if we ever start supporting some other `out` (; each `output` should be responsible for generating its own `eventhandler`. <- you may have already known that and that's why you suggested doing it this way. I really like that solution.

Let me know if I followed you correctly.

Best

Comment (SimonBaeumer) [reply pkg/runtime/runtime.go:127]: Yes you followed correctly! 
Indeed the `output` should be responsible for creating it's own `EventHandler`. 
If we want to support more outputs we could add a global variable which maintains a registry of all available output formats inside a hashmap, i.e.

```
// runtime.go
// {"cli": CLIEventHandler, "json": JSONEventHandler}
var OutputHandlers map[string]*EventHandler

func RegisterOutput(name string, eventHandler *EventHandler) {
     OutputHandlers[name] = eventHandler
}
``` 

The `cli.go` would register the `EventHandler` in an `init` func.

```
// cli.go
func init() {
    runtime.RegisterOutput(eventHandler)
}
```

Comment (dylanhitt) [reply pkg/runtime/runtime.go:127]: Cool, I hope to get this finished up by Tuesday evening.

Thanks again!

Comment (dylanhitt) [reply pkg/runtime/runtime.go:127]: I plan on getting to this, finding the time lately has been difficult.

Comment (dylanhitt) [reply pkg/runtime/runtime.go]: @SimonBaeumer the EventHandler made all this feel super nice. I didn't really focus on making it more configurable yet. I think that would be a task suited for when we have second `output` type. I figure it would something a long the lines of requiring all `outs` to implement an interface, but that's for a later PR.

**Comment by dylanhitt** [comment]
@SimonBaeumer I believe this ready for review

File: pkg/runtime/runner_test.go [hunk 5]
```diff
@@ -0,0 +1,59 @@
+package runtime
```
Comment (SimonBaeumer) [inline pkg/runtime/runner_test.go:1]: Test cases for the runner are missing, would be nice to add some test cases for it. Maybe `runtime_test.go` has something which can be moved in here.

File: pkg/runtime/runner_test.go [hunk 6]
```diff
@@ -0,0 +1,59 @@
...
+		Type: "docker",
+	}
+
+	nodes := []Node{
+		n1, n2, n3,
+	}
+	return nodes
+}
+
+func getExampleTestCases() []TestCase {
```
Comment (SimonBaeumer) [inline pkg/runtime/runner_test.go:42]: This function unused

File: pkg/app/test_command.go [hunk 7]
```diff
@@ -6,130 +6,136 @@ import (
...
+		result = convergeResults(result, newResult)
+	}
 
-	return results, nil
+	return result, nil
 }
 
-func testFile(filePath string, title string) (<-chan runtime.TestResult, error) {
-	content, err := readFile(filePath)
+func convergeResults(result runtime.Result, new runtime.Result) runtime.Result {
```
Comment (SimonBaeumer) [inline pkg/app/test_command.go:86]: This is something which could be done inside the `runtime` package in the future. For now it is okay that it the composition and aggregation is inside the `test_command.go`.

File: pkg/app/test_command.go [hunk 8]
```diff
@@ -6,130 +6,136 @@ import (
...
-				panic(fmt.Sprintf("%s: %s", f.Name(), err))
-			}
-
-			for r := range fileResults {
-				r.FileName = f.Name()
-				results <- r
-			}
+	for _, f := range files {
+		if f.IsDir() {
+			continue // skip dirs: TODO add support for walking
```
Comment (SimonBaeumer) [inline pkg/app/test_command.go:71]: Could you create an issue for this and remove the TODO commanet?

File: pkg/app/test_command.go [hunk 9]
```diff
@@ -6,130 +6,136 @@ import (
...
 	}
 
 	return nil
 }
 
-func testDir(directory string) (<-chan runtime.TestResult, error) {
+func testDir(directory string) (runtime.Result, error) {
+	result := runtime.Result{}
+
+	// TODO: validate entire dir before running tests: issue #129
```
Comment (SimonBaeumer) [inline pkg/app/test_command.go:63]: Removing TODO, it doen't add anything to the source because an issue exists. 
With these type of TODOs you create two sources of information, i.e. the issue gets closed the next programmer is confused by this comment.
The same reason applies of the `skip dirs` TODO comment.

File: pkg/runtime/runner_test.go (hunk 5 above)
Comment (dylanhitt) [reply pkg/runtime/runner_test.go:1]: Sure, I can just pull a similar test out of `runtime_test.go` and modify it for the `runner`. I was debating on mocking runner.go. But we would get into an interface implementation which isn't needed at the moment. Maybe another good refactor. I'll add this Friday morning.

File: pkg/app/test_command.go (hunk 7 above)
Comment (dylanhitt) [reply pkg/app/test_command.go:86]: opened #141

**Comment by dylanhitt** [comment]
@SimonBaeumer should be good to go now. I don't know if you want an update to the changelog since this is a just refactor. Unless you plan on incrementing versions. If so let me know.

**Comment by SimonBaeumer** [comment]
Merge! :)
